In [ ]:
# Numpy 개요와 사용
import numpy as np

np.array([1,2,3])

a = np.ones(2) # 2개의 1.로 이루어진 배열 ones default는 float64임
print(a) # [1. 1.]
print(a.dtype) # float64


[1. 1.]
float64


NameError: name 'int64' is not defined

In [6]:
np.ones(2, dtype=np.int64) # 2개의 1로 이루어진 배열, int64로 이루어진 배열



array([1, 1])

In [8]:
arr = np.array([2,1,4,5,32,12,13,12,312])
arr

array([  2,   1,   4,   5,  32,  12,  13,  12, 312])

In [9]:
arr.sort()
arr

array([  1,   2,   4,   5,  12,  12,  13,  32, 312])

In [10]:
arr = np.array([1,3,4,5,6,7,2,10])
arr

array([ 1,  3,  4,  5,  6,  7,  2, 10])

In [13]:
arr.argsort() # argsort는 인덱스를 반환한다. 

array([0, 6, 1, 2, 3, 4, 5, 7])

In [ ]:
print(np.arange(4)) # 0부터 4까지
print(np.arange(2, 9, 2)) # 2부터 9까지 2씩 증가
print(np.arange(1, 5, .7)) # .7은 소수점

[0 1 2 3]
[2 4 6 8]
[1.  1.7 2.4 3.1 3.8 4.5]


In [16]:
print(np.linspace(0, 10, 5)) # 0부터 10까지 5등분
print(np.linspace(0, 10, num = 5)) #
print(np.linspace(0, 10, num = 11))

[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [17]:
array_example = np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]]])
array_example

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [18]:
array_example.ndim

3

In [19]:
array_example.size

16

In [ ]:
array_example.shape # 

(1, 4, 4)

In [22]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b = a.reshape(3, 2) # 3행 2열로 변환
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
a = np.array([1,2,3,4,5,6]) # 1차원 배열
a.shape # (6,) 튜플형태로 출력 요소 개수 6개 1차원배열

(6,)

In [ ]:
b = np.expand_dims(a, axis = 1) # axis = 1은 열을 추가하는 것
b.shape

(6, 1)

In [ ]:
b # 6행 1열

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [28]:
c = np.expand_dims(a, axis = 0) # axis = 0은 가장 앞에 차원을 추가하는 것
c.shape # (1, 5)

(1, 6)

In [29]:
data = np.arange(30)

data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
data.reshape(2, 5, 3) # 3차원 5행 2열

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [32]:
a = np.arange(1,31).reshape(5, 6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [33]:
a[:,:] # 전체

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [34]:
a[:2] # a의 0번째와 1번째

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [35]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [37]:
a[:,2:5] # a의 모든 행, 2열 이하

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [38]:
a[1:3, 2:5] # 행은 1~2,  열은 2~4

array([[ 9, 10, 11],
       [15, 16, 17]])

In [47]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a<5)
print(a[a<5])
print(a[a>5])
cond = (a > 2) & (a < 11)
print(a[cond])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ True  True  True  True]
 [False False False False]
 [False False False False]]
[1 2 3 4]
[ 6  7  8  9 10 11 12]
[ 3  4  5  6  7  8  9 10]
