In [2]:
import numpy as np

a = np.array([20, 30, 40, 50])
a

array([20, 30, 40, 50])

In [3]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [5]:
c = a - b
c

array([20, 29, 38, 47])

In [7]:
data  = np.array([1,2])
ones = np.ones(2, dtype = int)
print(data + ones)
print(data - ones)
print(data * ones)
print(data / ones)

[2 3]
[0 1]
[1 2]
[1. 2.]


In [8]:
arr.sum() # 전체 원소의 합
arr.sum(axis = 0) # 열의 합
arr.sum(axis = 1) # 행의 합


NameError: name 'arr' is not defined

In [9]:
b = np.array([[1,2],[3,4]])
b 

array([[1, 2],
       [3, 4]])

In [14]:
print(b.sum())
print(b.sum(axis=0)) # 열의 합
print(b.sum(axis=1)) # 행의 합

10
[4 6]
[3 7]


In [15]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [ ]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])  
data    

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
ones_row = np.ones(3, dtype=int)
ones_row
print(data + ones_row)
print(data * ones_row)
print(data - ones_row)
print(data / ones_row)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [26]:
a = np.array([0.0, 10.0, 20.0, 30.0])
a = a.reshape(4,1)
print(a)
b = np.array([1.0,2.0,3.0])
print(b)
print(a + b)

[[ 0.]
 [10.]
 [20.]
 [30.]]
[1. 2. 3.]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [27]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
print(a)
b = np.array([1.0,2.0,3.0])
print(b)
print(a + b)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
[1. 2. 3.]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
